version: '3'

services:
  prediction_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - type: bind
        source: ./prediction_app/
        target: /prediction_app
    ports:
      - 8501:8501
    depends_on:
      - prediction_api

  prediction_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8001:8001
    volumes:
      - type: bind
        source: ./prediction_api/
        target: /prediction_api