version: '3'

services:
  prediction_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 8501:8501
    depends_on:
      - prediction_api

  prediction_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8001:8001